version: "2"

linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt

linters-settings:
  exhaustive:
    default-signifies-exhaustive: false
